# Generated by Django 2.0.13 on 2019-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(blank=True, max_length=50)),
                ('ein1', models.CharField(blank=True, max_length=50)),
                ('ein2', models.CharField(blank=True, max_length=50)),
                ('ein3', models.CharField(blank=True, max_length=50)),
                ('nid', models.CharField(blank=True, max_length=50)),
                ('amount', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
